#This file was automatically generated by the gem ajaxful_rating https://github.com/edgarjs/ajaxful-rating
#The corresponding database table: rates
#Rate describes the average rating of a user; links the rate model to the User model

class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  validates_numericality_of :stars, :minimum => 1
  
  attr_accessible :rate, :dimension
end
